## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway Internet-Gateway-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.835Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Internet Gateway-soavcn-phx"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_network_security_group bastion-nsg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-10-25T20:54:13.734Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "bastion-nsg"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_network_security_group db-nsg {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:26:45.264Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "db-nsg"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_network_security_group_security_rule bastion-nsg_network_security_group_security_rule_1 {
  description = "SSH access inbound"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.bastion-nsg.id
  protocol                  = "6"
  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "22"
      min = "22"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule bastion-nsg_network_security_group_security_rule_2 {
  description               = "Bastion to all"
  destination               = "11.0.0.0/16"
  destination_type          = "CIDR_BLOCK"
  direction                 = "EGRESS"
  network_security_group_id = oci_core_network_security_group.bastion-nsg.id
  protocol                  = "all"
  #source = <<Optional value not found in discovery>>
  source_type = ""
  stateless   = "false"
}

resource oci_core_network_security_group_security_rule db-nsg_network_security_group_security_rule_1 {
  description = "DBCS / ATP DB traffic from CIDR"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.db-nsg.id
  protocol                  = "6"
  source                    = "11.0.0.0/16"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "1522"
      min = "1521"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}

resource oci_core_network_security_group_security_rule db-nsg_network_security_group_security_rule_2 {
  description = "APEX/ORDS 443 traffic"
  #destination = <<Optional value not found in discovery>>
  destination_type          = ""
  direction                 = "INGRESS"
  network_security_group_id = oci_core_network_security_group.db-nsg.id
  protocol                  = "6"
  source                    = "11.0.0.0/16"
  source_type               = "CIDR_BLOCK"
  stateless                 = "false"
  tcp_options {
    destination_port_range {
      max = "443"
      min = "443"
    }
    #source_port_range = <<Optional value not found in discovery>>
  }
}


resource oci_core_service_gateway Service-Gateway-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:39.119Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Service Gateway-soavcn-phx"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.phx.aaaaaaaasgvxtsqcj2jkt2xppos637xym4ab5qqqptgwjd4guj7v3d26t7oa"
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_subnet DB-Subnet-soavcn-phx {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "11.0.2.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-10-25T20:17:23.242Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.soavcn-phx.default_dhcp_options_id
  display_name    = "DB Subnet-soavcn-phx"
  dns_label       = "db"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.Route-Table-for-Private-Subnet-soavcn-phx.id
  security_list_ids = [
    oci_core_vcn.soavcn-phx.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.soavcn-phx.id
}


resource oci_core_subnet Private-Subnet-soavcn-phx {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "11.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.845Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.soavcn-phx.default_dhcp_options_id
  display_name    = "Private Subnet-soavcn-phx"
  dns_label       = "app"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.Route-Table-for-Private-Subnet-soavcn-phx.id
  security_list_ids = [
    oci_core_security_list.Security-List-for-Private-Subnet-soavcn-phx.id,
  ]
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_subnet Public-Subnet-soavcn-phx {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "11.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.934Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.soavcn-phx.default_dhcp_options_id
  display_name    = "Public Subnet-soavcn-phx"
  dns_label       = "lbr"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.soavcn-phx.default_route_table_id
  security_list_ids = [
    oci_core_vcn.soavcn-phx.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_vcn soavcn-phx {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "11.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:37.982Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "soaVCN-phx"
  dns_label    = "soavcnphx"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  #is_ipv6enabled = <<Optional value not found in discovery>>
}


resource oci_core_default_dhcp_options Default-DHCP-Options-for-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:37.982Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name     = "Default DHCP Options for soaVCN-phx"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  manage_default_resource_id = oci_core_vcn.soavcn-phx.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "soavcn-phx.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway NAT-Gateway-soavcn-phx {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.862Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "NAT Gateway-soavcn-phx"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  vcn_id       = oci_core_vcn.soavcn-phx.id
}

resource oci_core_route_table Route-Table-for-Private-Subnet-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.833Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Route Table for Private Subnet-soavcn-phx"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.NAT-Gateway-soavcn-phx.id
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-phx-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.Service-Gateway-soavcn-phx.id
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_default_route_table Default-Route-Table-for-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:37.982Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Default Route Table for soaVCN-phx"
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  manage_default_resource_id = oci_core_vcn.soavcn-phx.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.Internet-Gateway-soavcn-phx.id
  }
}

resource oci_core_security_list Security-List-for-Private-Subnet-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:38.830Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Security List for Private Subnet-soavcn-phx"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "11.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "All intra-private comms"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "11.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For LB to WLS managed servers"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "9073"
      min = "9073"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Bastion WLS Console access"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "7002"
      min = "7002"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Bastion 443 for DB tools"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Bastion WLS Console"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "7001"
      min = "7001"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.soavcn-phx.id
}

resource oci_core_default_security_list Default-Security-List-for-soavcn-phx {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-26T12:24:37.982Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/andrew.gregory@oracle.com"
  }
  display_name = "Default Security List for soavcn-phx"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-03-26T12:23:49"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "11.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "All Intra-VCN traffic"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "11.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.soavcn-phx.default_security_list_id
}

